version: '3.8'

services:
  # ========== 数据库服务 ==========
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: flight_booking
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  # ========== 服务注册中心 ==========
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root123
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - "8848:8848"
    volumes:
      - ./nacos/logs:/home/nacos/logs

  # ========== 分布式事务协调器 ==========
  seata:
    image: seataio/seata-server:1.7.0
    container_name: seata-server
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_started
    environment:
      SEATA_IP: seata
      STORE_MODE: db
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root123
    ports:
      - "8091:8091"
    volumes:
      - ./config/seata/file.conf:/seata-server/resources/file.conf

  # ========== 消息队列 (KRaft 模式，无需 ZooKeeper) ==========
  kafka:
    image: bitnami/kafka:3.8
    container_name: kafka-server
    environment:
      # KRaft 模式配置
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # 其他配置
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_KRAFT_CLUSTER_ID: "abcdefghijklmnopqrstuv"
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka-data:/bitnami/kafka

  # ========== 缓存服务 ==========
  redis:
    image: redis:7.0
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

# ========== 数据卷定义 ==========
volumes:
  mysql-data:
  kafka-data:
  redis-data: